# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4c574ffe6a9772789a1c99209abce3a7340e8d49950a6f40f25444972b5f6abece908ef6378645c77c606e9f6d40584575350d2970e069c6bdbc18306a4ae27

test:
  secret_key_base: e4f2a194f84fb16e5ec36be3e460c86d0d7859dd6a109e053ddfa0f5cc44da4c614dcb6013fc71eebe11e5248b2ae39c37ab4ff8cdb5ce709c94b2a4eaaa4d3b



# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>